# Generated by Django 5.0.3 on 2024-11-07 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_csv_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='csv',
            name='old_csv',
            field=models.FileField(blank=True, null=True, upload_to='Upload/old_csv_file/'),
        ),
    ]
